language: python
python:
  - "3.7.12"

# # to be able to use Docker images
# services:
#   - docker

# script:
#   - docker pull lyaqing/snakemake_rnaseq:0.3.2
#   - docker run -v $PWD:/home/snakemake lyaqing/snakemake_rnaseq:0.3.2 -n