name: rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - snakemake = 8.10.6
  - python = 3.6.15
  - fastp = 0.23.4
  - fastqc = 0.12.1
  - qualimap = 2.2.2d
  - multiqc = 1.21
  - star = 2.7.10b
  - subread = 2.0.6
  - hisat2 = 2.2.1
  - stringtie = 2.1.7
  - htseq = 0.12.4
  - salmon = 1.10.1
  - sailfish = 0.9.0
  - boost = 1.60.0
  - kallisto = 0.48.0
  - rsem = 1.2.28
  - bowtie = 1.3.1
  - pandas = 1.1.5
  - r-tidyverse = 1.3.1
  - yaml = 0.2.5
  - jupyterlab = 3.2.1
