name: rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - snakemake = 8.10.6
  - python = 3.6.8
  - fastp = 0.23.4
  - fastqc = 0.12.1
  - qualimap = 2.2.2
  - multiqc = 1.21
  - star = 2.7.10b
  - subread = 2.0.3
  - hisat2 = 2.2.1
  - stringtie = 2.2.1
  - htseq	= 2.0.2
  - salmon = 1.10.1
  - sailfish = 0.9.0
  - boost = 1.60.0
  - kallisto = 0.48.0
	- rsem = 1.3.3
  - bowtie = 1.3.1
  - bowtie2 = 2.5.3
  - pandas = 2.2.2
  - r-tidyverse = 2.0.0
  - yaml = 0.2.5
  - jupyterlab = 4.1.6
